### PR TITLE
Allow specifying images to reuse cache from

### PR DESCRIPTION
**Pull request by yuvipanda**
This lets us explicitly specify images that repo2docker
should try to re-use cached layers from. Docker normally only
looks for layers from images that were *built* locally - if
we want it to look in images that were *pulled* from a registry,
we need to specify it here.

This isn't a problem on binder, since we don't pull images from
elsewhere yet. However, this *is* a problem for hubploy, and
would make the life of https://github.com/yuvipanda/hubploy/pull/4
much easier.

### CODE REVIEW

**Comment by yuvipanda** [comment]
I am not sure at all how to test this.

**Comment by betatim** [comment]
I like it! Two ponderings:

* should we stick to using exactly the same command-line argument name as `docker build` uses instead of changing the name slightly?
* can we offer some (automatic) behaviour to the unsuspecting user that "does the right thing" and speeds up their local builds? See last paragraph for some thoughts

re: testing, will `docker inspect` tell you if a layer was built or taken from the cache? Alternatively I think a layer that is shared between two images should have the same ID in both so if we `inspect` the cache-from image and the newly built one we should be able to find shared layers.

---

We have discussed building and pushing images that contain the layers before copying in the repo contents for each build pack to docker hub. This would speed up the 100% shared part of the builds, for the user who has never built that buildpack before locally. If we do this then we could have a `--cache-from=auto` setting that adds all those images to the list. Would we end up pulling all images or only those that are used?

There is also #310 for which this PR could be useful.

**Comment by yuvipanda** [comment]
> I like it! Two ponderings:
> 
>     * should we stick to using exactly the same command-line argument name as `docker build` uses instead of changing the name slightly?

Yeah, that sounds like a good idea.

>     * can we offer some (automatic) behaviour to the unsuspecting user that "does the right thing" and speeds up their local builds? See last paragraph for some thoughts

This already happens for images already built locally. --cache-from is only needed to re-use cache from images *pulled* from an external repository.

> 
> re: testing, will `docker inspect` tell you if a layer was built or taken from the cache? Alternatively I think a layer that is shared between two images should have the same ID in both so if we `inspect` the cache-from image and the newly built one we should be able to find shared layers.

Since cache is used both for images already built locally and images pulled from a remote registry, there's no easy way to find out if this was effective or not.

> 
> We have discussed building and pushing images that contain the layers before copying in the repo contents for each build pack to docker hub. This would speed up the 100% shared part of the builds, for the user who has never built that buildpack before locally. If we do this then we could have a `--cache-from=auto` setting that adds all those images to the list. Would we end up pulling all images or only those that are used?

This seems like a larger discussion that we should have in a separate issue.

> There is also #310 for which this PR could be useful.

**Comment by yuvipanda** [comment]
Maybe from https://github.com/jupyter/repo2docker/pull/482#issuecomment-444778403, another option here is to mock the docker client. I think that'd be much easier, actually! The integration test would be testing that docker itself works fine, while we only care wether we pass through the param properly

**Pull request merged**
