### PR TITLE
Change faq to rst

### PR DESCRIPTION
**Pull request by evertrol**
Follow up to #421, merge after that.

- allows for admonition
- fixes reST/Sphinx directive used in Markdown
- removes dead link

### CODE REVIEW

**Comment by evertrol** [comment]
DO NOT MERGE YET!

Dependent on #421: once that is merged, this PR will be updated and can be merged.

**Comment by betatim** [comment]
(I updated the top comment to mention that this follows on from #421.)

**Comment by choldgraf** [comment]
I'd be +1 on adding a `How to edit your files interactively` section to `Howto`. Nice addition @evertrol !

**Comment by betatim** [comment]
Merged!

**Pull request merged**
