### PR TITLE
bump versions and refreeze

### PR DESCRIPTION
**Pull request by minrk**
gets notebook 5.6, which includes fixes that blocked 5.5 in #325

A subsequent PR (@GladysNalvarte is working on this) can set the display_url so that it's guaranteed to be correct when run in repo2docker, which has never been the case before.

### CODE REVIEW

**Comment by betatim** [comment]
For my education: what is this display_url thing?

Do you know where we picked up twisted and zope.interfaces as new dependencies?

**Comment by jzf2101** [comment]
I'm ok with this tho we'll need to update again as soon as jupyterlab has their next release as well.

**Comment by minrk** [comment]
@betatim #358 is aiming at #325. notebook 5.6 allows setting `NotebookApp.custom_display_url`, which lets repo2docker tell the container exactly what to log for the "copy this URL" bit. We can always get that right, because *repo2docker* knows the right URL (even when using docker machine), while the container can't know without being told.

**Comment by betatim** [comment]
If we are happy with the extra new dependencies: merge!

**Comment by SylvainCorlay** [comment]
@minrk @betatim it appears that this change was just applied to the prod binder and unfortunately, it will break all C++ binders 😒 

the xeus-cling kernel requires a binary-compatible version of `pyzmq`, and we use a build from the QuantStack channel for this, which is in conflict with your pinning of pyzmq.

Would it be possible to revert that change and use the previous environment until we figure out a solution?

**Comment by jzf2101** [comment]
We need to create a new release of r2d - how would you suggest we fix this

**Pull request merged**
