### PR TITLE
Julia PackageCompiler [WIP] 

### PR DESCRIPTION
**Pull request by arnavs**
This handles `repo2docker`'s side of the changes in #686.

See https://github.com/arnavs/binder-bakery for an example repo to test against. 

The main changes to code are: a `self.baked_goods()` method to digest the `[packagecompiler]` bit of TOML, and then feeding that into the Julia script (if the TOML section is present.)

cc: @jlperla, @betatim 

Edit: Will change the names to be less whimsical.

### CODE REVIEW

**Comment by arnavs** [comment]
@betatim Ready for you.

**Comment by arnavs** [comment]
Sorry, made a few fixes. Turns out the errors weren't simply local. 

@betatim, do you know how I could run the output of `get_assemble_scripts(self)` with more permissions? It's successfully building a new system image, but returning an `EACCESS` error when we try to unlink the old one.

Note: PackageCompiler is still fragile. This is the "state of the art" branch, but it's still rickety.

**Comment by arnavs** [comment]
Just wanted to check in about this (@betatim and others.) The changes we've made to the `get_assemble_script` are correct (i.e., it returns the right commands.) The problem is that whatever's running them doesn't have the appropriate unlinking permissions.

**Comment by betatim** [comment]
I've not had time to read and think about this PR yet, sorry! Fantastic weather for outdoors activities and general busy-ness. I will try and look at this towards the end of this week.

I did want to stop by to let you know that we merged #699 which means we are now using [black](https://black.readthedocs.io/en/stable/) as code formatter. The motivation for doing this is to have a uniform style that will make it easier to read code.

You can install black with `pip install black` and run it on your code with `black .` in the top level directory of this repo. Travis enforces this style for all new PRs. For existing PRs (like this one) the best course of action is to rebase your branch on the latest `master`.

We also have a pre-commit hook to run black automatically which I'd install if you contribute to repo2docker more frequently.

We added a few sentences to the contributing docs https://repo2docker.readthedocs.io/en/latest/contributing/contributing.html#code-formatting. Feedback welcome (not on the choice of black though, that is final :) )

**Comment by arnavs** [comment]
Sounds good, I'll rebase and run the linter. And likewise, the weather here is almost unbearably good. 

Whenever you get around to it, the tl;dr is that we can spit out the right commands in the Julia assemble script. They're just not being run with the appropriate permissions (at the stage where we unlink the old Julia system image, and link the new one we've built.)

**Comment by arnavs** [comment]
Hey @betatim, do you think you'll be able to take a look this week?

**Comment by arnavs** [comment]
I'll close this PR per @davidanthoff's comments in the issue. We can re-open it if we decide to go this route.

**Comment by betatim** [comment]
Thanks a lot for all the work on this @arnavs! Sorry I didn't get to this earlier/at all. Maybe in this case we lucked out though given @davidanthoff's thoughts.

**Pull request closed without merging**
