### PR TITLE
Add test to check for extra directory on PATH

### PR DESCRIPTION
**Pull request by betatim**
Follow up #311 and add a simple test

### CODE REVIEW

**Comment by yuvipanda** [comment]
I've incorporated this into #313

**Comment by choldgraf** [comment]
FWIW I think a better way to handle these situations it to put the word "closes #NNN" in the top-level comment of the PR. That way, whenever the PR is merged GitHub will automatically close the issue corresponding to `NNN`.

**Comment by betatim** [comment]
Yes that is what we normally do. Not sure what you mean in this case though as this was a followup to a PR that had been merged. There was no corresponding issue. Then Yuvi cherry picked the commit from here into a new PR.

**Comment by choldgraf** [comment]
ahh my bad, I had a brain fart and thought this was an issue, not a PR! Sorry for the noise

**Pull request closed without merging**
