### PR TITLE
[WIP] add hydroshare as a content provider

### PR DESCRIPTION
**Pull request by sblack-usu**
https://www.hydroshare.org is a data repository for Hydrologists to share water data.

I will add tests soon

### CODE REVIEW

**Comment by nuest** [comment]
@sblack-usu Hi! I've also implemented a content provider and made some changes in the class hierarchy (see #788). Your code needs an update if #788 is merged before this one, and I'm happy to do that while the new developments are still in my head :-).

_What's your plan regarding the tests?_

**Comment by sblack-usu** [comment]
@nuest - I'll go ahead and update to the new class hierarchy and get the tests in soon.  Haven't been able to prioritize this work since I got back from the conference, but will have time this week.

**Comment by sblack-usu** [comment]
I didn't have time the other week, but I'm working on the tests now, so 🤞 it's enough.

**Comment by sblack-usu** [comment]
reopening with a new branch

**Comment by sblack-usu** [comment]
reopened in #800

**Pull request closed without merging**
