### PR TITLE
[MRG] Make sure the exit status gets passed along in Azure pipelines

### PR DESCRIPTION
**Pull request by betatim**
See if @manics idea from https://github.com/jupyter/repo2docker/issues/744#issuecomment-530867092 is it. Don't merge for now as it contains a test that always fails.

### CODE REVIEW

**Comment by betatim** [comment]
Let's see if this produces "the right failures" and then I'll remove the always fail test.

**Comment by betatim** [comment]
Looks like it all works as expected now. I remove the lint step from Azure. We should add it back before we finally remove travis.

We need to figure out what a nice way to change the test command when the "job type" is "lint".

**Comment by betatim** [comment]
cc @minrk

**Comment by minrk** [comment]
Had to restart some Azure tests due to network errors. Not sure what's up there, but it all succeeded eventually.

**Pull request merged**
