### PR TITLE
[MRG] Update base image used for memory limit checks

### PR DESCRIPTION
**Pull request by betatim**
Locally this still fails :-/

### CODE REVIEW

**Comment by betatim** [comment]
It seems like (locally) the limit doesn't actually get applied/used :-/ I'll need a bit of time to investigate what is going on.

**Comment by Xarthisius** [comment]
> Locally this still fails :-/

@betatim I vaguely remember that I had problem imposing mem limits for docker using python API. It accepted the size notation but it wasn't setting the limit properly. I'd try to use number of bytes explicitly.

**Comment by betatim** [comment]
Mystery solved. The [docker-py documentation](https://docker-py.readthedocs.io/en/stable/api.html#module-docker.api.build) says that a value of `-1` will disable swap, which we were using. However https://docs.docker.com/engine/reference/commandline/build/ specifies that `-1` means "unlimited swap". In the [docker-py code](https://github.com/docker/docker-py/blob/23c5c001c6345c431fe31d8dfb62a38cc59720bc/docker/api/build.py#L123-L175) I can't find anywhere where they do processing of the values we passed in.

Updated our code to reflect this new knowledge. Though I am confused why all tests have passed on travis (for 5adc4b2) when they fail locally. Speculation: there is no swap for the whole machine on travis?

**Comment by yuvipanda** [comment]
I dug around a bit more, and found https://github.com/docker/docker.github.io/issues/4335. Is there a reason we're setting memory swap to be one byte more, instead of exactly the same?

**Comment by betatim** [comment]
When I had it set to 1 (a guess for "if we can't disable then let's use 1byte") I got an error the said "swap has to be bigger than memory limit", I didn't check if they actually meant "equal or larger". Checking now.

**Comment by betatim** [comment]
Looks like setting it to the same amount works! That is a nicer solution :D Thanks for asking.

**Comment by yuvipanda** [comment]
@betatim awesome! I changed the comment around it a little, otherwise it LGTM.

**Comment by yuvipanda** [comment]
Merged with @betatim's blessing. <3

**Pull request merged**
