### PR TITLE
Replace theme with alabaster

### PR DESCRIPTION
**Pull request by willingc**
For better display on RTD, let's change the theme to the default, generic alabaster theme instead of the jupyter theme. cc/ @Carreau @choldgraf

### CODE REVIEW

**Comment by choldgraf** [comment]
agree this is a good decision!

as it's design and that affects the whole site, I'll let somebody else (maybe @yuvipanda or @Carreau weigh in before merging)

**Comment by yuvipanda** [comment]
I approve!

**Comment by willingc** [comment]
Going to merge since I don't see @Carreau objecting ;-)

**Comment by Carreau** [comment]
I object to not merging :-) I should be able to start pitching in from a
computer later today.

**Pull request merged**
