### PR TITLE
Remove ability to set UID of the user added to the generated image

### PR DESCRIPTION
**Pull request by juanesarango**
Related with issue #223.

### CODE REVIEW

**Comment by betatim** [comment]
Comment with some motivation for this change https://github.com/jupyter/repo2docker/issues/223#issuecomment-393280799

Have you already experimented with removing options to see which ones in particular have to be removed and which ones can stay?

**Comment by juanesarango** [comment]
Hi betatim, 

So, I think both `--disabled-password` and `--gecos` are needed to avoid the command to [ask for prompt input](https://askubuntu.com/questions/94060/run-adduser-non-interactively). Even thought that docker will skip and pass the defaults for those inputs, and that if you don't pass `--password` it will be disabled by default.

I see that the problem is with `--uid` option only. So I made some changes to my PR to only remove `--uid` and keep the other options, as I saw some travis tests failed.

**Comment by choldgraf** [comment]
hey all - just a ping to see where we are on this PR - it seems from @betatim 's latest comment that there's some uncertainty as to whether this can be implemented without breaking other functionality?

**Comment by betatim** [comment]
Removing the ability to set the UID is definitely not something we can or should do. I'd close this PR and start a new one to tackle the problem that users whose accounts are centrally managed run into #223. It isn't clear to me why having your account centrally managed causes this problem. Setting the UID to something different from your users account seems to fix the problem, but doing so has other drawbacks (permissions when mounting directories from the host).

**Pull request closed without merging**
