### PR TITLE
Bump nteract version to 2.0.0

### PR DESCRIPTION
**Pull request by yuvipanda**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Thank you!

**Comment by choldgraf** [comment]
merging since we have a 🤧 nteract right now!

**Comment by rgbkrk** [comment]
I am forever using 🤧 as the :new: 🆕  emoji.

**Comment by choldgraf** [comment]
I'm gonna restart the 3 travis tests that failed or stopped here: https://travis-ci.org/jupyter/repo2docker/builds/486567146?utm_source=github_status&utm_medium=notification

let's see if we can figure out why they didn't pass (which I assume is related to why tests failed in the binder deploy)

**Pull request merged**
