### PR TITLE
Remove ipyleaflet dependency from test

### PR DESCRIPTION
**Pull request by betatim**
Not sure it adds anything to the test except more stuff to install which makes the test slower.

### CODE REVIEW

**Comment by yuvipanda** [comment]
I think this is the only place we test that notebook extensions work. These two lines don't do the actual install - that's in requirements.txt. We should probably just keep these.

**Comment by betatim** [comment]
If this is the only place we test this we should keep it. Note though that the `requirements.txt` is deleted in this PR.

**Comment by yuvipanda** [comment]
Ah, fair. I think we should keep it because we aren't testing notebook extensions anywhere else.

**Comment by betatim** [comment]
Closing this then. Maybe in the future we can investigate if there is a notebook extension with no dependencies that we can use in tests to speed up install times.

**Pull request closed without merging**
