### PR TITLE
refreeze environments

### LINKED ISSUE #257: update ipykernel to work with tornado 5 so Python 2 kernels work again
Presently, the Python 2 kernels in both  https://github.com/binder-examples/python2_runtime and https://github.com/binder-examples/python2_with_3 , go dead before any code can be run.

Min RK @minrk noted:
>Min RK @minrk 13:36 @fomightez indeed, tornado was allowed to be updated to 5.0, but ipykernel is pinned to an earlier version that doesn't work with tornado 5. This needs to be fixed in repo2docker.

### PR DESCRIPTION
**Pull request by minrk**
- bump ipykernel to 4.8.2
- pin tornado to 4.5.3

closes #257

### CODE REVIEW

**Comment by minrk** [comment]
I'd like to deploy this as part of https://github.com/jupyterhub/mybinder.org-deploy/pull/502 which also needs to bump the image prefix

**Comment by willingc** [comment]
@minrk Merging. Thanks. Is there a specific conflict re: tornado to pin to 4.5.3.?

**Comment by minrk** [comment]
Just to be consistent, since tornado 5 hasn't landed on conda-forge and there have been a few edge cases where tornado 5 doesn't quite work. I think we can be a bit conservative and pick up tornado 5 after a bit more stabilizing elsewhere.

**Comment by willingc** [comment]
Makes complete sense. Thanks @minrk.

**Pull request merged**
