### PR TITLE
Fix indentation causing only last line of apt.txt to be parsed

### PR DESCRIPTION
**Pull request by nmih**
Parsing apt.txt was only appending the last package to the list of packages to install. Fixed indentation to append all packages.

### CODE REVIEW

**Comment by betatim** [comment]
Whoops! Thanks for making this your first contribution to repo2docker :)!

Could you also add a test to make sure this bug doesn't come back? Maybe copy [this test](https://github.com/jupyter/repo2docker/blob/f7096caccddf333b84abcc0e308f45e2299aa146/tests/venv/apt-packages/apt.txt) and use an apt.txt with two or more lines, then check that both bot installed.

**Comment by nmih** [comment]
Sure thing, done!

**Comment by betatim** [comment]
`rolldice` and `sl` get installed in `/usr/games` which doesn't seem to be on the `PATH` so the test fails. Does someone with more ubuntu experience know if this is on purpose/how to deal with this?

Otherwise we could pick two other packages to install maybe.

**Comment by nmih** [comment]
Ah my bad, didn't realize that was the case. I changed it to two other small packages that install to /usr/bin instead for now.

**Comment by betatim** [comment]
LGTM! Merging.

**Comment by betatim** [comment]
Welcome to another first time contributor!

**Pull request merged**
