### PR TITLE
Bump default python version to 3.7

### PR DESCRIPTION
**Pull request by yuvipanda**

### CODE REVIEW

**Comment by betatim** [comment]
#533 might be relevant and there is another issue (or PR) where we discuss what "LTS" means in terms of the default Python version.

**Comment by yuvipanda** [comment]
@betatim that issue is around RStudio. Did you mean https://github.com/jupyter/repo2docker/issues/521? That mentions LTS.

I think #521 is unrelated, since it's about what version of python the *repo2docker code* should support, rather than the default for *images built with repo2docker*.

**Comment by betatim** [comment]
Yes I think I meant #521. Not sure why I wrote 533. Looking now I might have meant #522 and the discussion about what the default version of Python is that will be installed in a conda environment.

I think the discussion in #521 is related despite it being about the version of Python required to run r2d. We should make some promises about which version of Python ends up in an image by default. I consider the version of the tools we install part of what we version. Similar to a library that versions its API and default arguments etc.

I don't know what our strategy should be but I do think we should decide on a strategy and write it down so that users can rely on it and plan accordingly.

**Comment by yuvipanda** [comment]
Picking back up on this, I'd say the smallest thing we can say is that 'bumping default versions means we bump repo2docker version too'. This also ties back into writing a 'repo2docker spec' that will specify the default language versions (along with how each file is interpreted).

For now, I'd say bumping the version means we've to make a new release. How does that sound, @betatim and @minrk?

**Comment by minrk** [comment]
I think that's sensible. Bumping the default minor version of Python would be a major version upgrade for repo2docker.

**Comment by yuvipanda** [comment]
Updated, let's see if things pass

**Comment by betatim** [comment]
I'm still hesitant to bump the default version of Python. Most research code lags behind by a country mile, people might not have pinned the version of Python they want and we don't yet have support to pin repo2docker versions for a repo. Mostly I am worried about breaking user's repos that used to work but now don't anymore.

Compromise: we add a note/new section/howto in the docs that explains how to pin the version of Python (`runtime.txt` or `environment.yml`) that we can send people to that will come because we broke stuff: look this is how you pin it which is a good idea anyway and will un-break you. WDY?

**Comment by yuvipanda** [comment]
@betatim Sounds like a good idea to me. Where do you think that should live?

I see https://mybinder.readthedocs.io/en/latest/config_files.html#runtime-txt-specifying-runtimes now...

**Comment by betatim** [comment]
I think I'd put it in the repo2docker docs (and link from the binder docs?)

There is already https://repo2docker.readthedocs.io/en/latest/howto/languages.html#specifying-a-version-of-python so maybe adding a FAQ with a title that speaks to people who are grumpy because their stuff just broke like: "How to select the version of Python used?" or "How should I freeze the version of Python used?" or some such that points to that section is enough.

---

We should try and (re)organise our various documentations? I always feel lost in them, especially what is/should be where.

**Comment by yuvipanda** [comment]
Given my current situation, I'm trying to minimize typing where I can. Would be lovely if someone other than me could get the doc bit in. Thanks.

**Comment by minrk** [comment]
Updated some docs on pinning runtime. I think we already had everything being asked for, I just updated the language a bit and added a reference to the default version that's pulled from the code so it'll always be correct.

- FAQ already has how to pin Python as the first two Qs, it is also mentioned in config_files and the Python section of howto/languages. Added some detail about which version is default and links to config_files
- clarification in a few places that runtime.txt is only for use with environment specifications that do not support specifying the runtime (i.e. only with requirements.txt, not environment.yml)
- get default Python version from the code so that it's harder to fall out of date

What I didn't do is add a whole new section on best practices on pinning because I think this is pretty nuanced and not a last-minute thing to do for release (the *worst* thing you can do is strictly pin only some dependencies, e.g. a requirements.txt that looks like):

```
numpy==1.15.3
```

without pinning Python as well, or with other unpinned packages, e.g. just `matplotlib`.

It's better to either:

- loosely specify all requirements, including Python, to ensure you get the most compatible latest combination of everything, or
- strictly specify all requirements and all their dependencies, including Python, to ensure you get a known-good combination frozen in time.

**Comment by betatim** [comment]
Thanks!

**Comment by yuvipanda** [comment]
Thank you very much, @minrk and @betatim!

**Pull request merged**
