### PR TITLE
[MRG] - fix repo2docker logo in Sphinx docs

### PR DESCRIPTION
**Pull request by trallard**
This PR fixes the display of the repo2docker logo in the docs navigation bar. 

This is how it currently looks:
Roadmap_—_repo2docker_0_11_0_75_gebf973a_documentation

This is the navbar with the fix:

jupyter-repo2docker_—_repo2docker_0_11_0_75_gebf973a_documentation

The logo should now display properly regardless of the screen size

### CODE REVIEW

**Comment by betatim** [comment]
Screenshot 2020-06-05 at 15 18 15

this is what it looks like for me now :-/ Did you try out what happens if we remove all the "custom" stuff from our CSS and use what the template does by default?

**Comment by manics** [comment]
It depends on your browser, but it looks like a typical responsive design problem (ran into something similar on another project). On my phone:
Screenshot_20200605-151331-01

There's a similar problem with z2jh:
Screenshot_20200605-151432-01

Could we maybe fix this in the theme instead of individual repos?

**Comment by trallard** [comment]
So I have checked the display in multiple browsers and resolutions:

## No fix (current display)

- Wide screen 


jupyter-repo2docker_—_repo2docker_0_11_0_75_gebf973a_documentation_and_jupyter-repo2docker_—_repo2docker_0_11_0_75_gebf973a_documentation_and_Ergodox_EZ_Configurator


- Ipad


jupyter-repo2docker_—_repo2docker_0_11_0_75_gebf973a_documentation_and_jupyter-repo2docker_—_repo2docker_0_11_0_75_gebf973a_documentation_and_Ergodox_EZ_Configurator


## With Fix

- Wide browser

jupyter-repo2docker_—_repo2docker_0_11_0_75_gebf973a_documentation_and_jupyter-repo2docker_—_repo2docker_0_11_0_75_gebf973a_documentation_and__🏝live-islands-turnips_-_Discord

- IphoneX 

jupyter-repo2docker_—_repo2docker_0_11_0_75_gebf973a_documentation_and_jupyter-repo2docker_—_repo2docker_0_11_0_75_gebf973a_documentation_and_Ergodox_EZ_Configurator

- IPad 

jupyter-repo2docker_—_repo2docker_0_11_0_75_gebf973a_documentation_and_jupyter-repo2docker_—_repo2docker_0_11_0_75_gebf973a_documentation_and_Ergodox_EZ_Configurator


It seems by removing    https://github.com/jupyter/repo2docker/blob/ebf973ab60e0d476f3a69f412b2546bfff57fe20/docs/source/_static/custom.css#L1-L3 

The rendering problem is sorted 


jupyter-repo2docker_—_repo2docker_0_11_0_75_gebf973a_documentation

Though normally prefer using `max-width` plus flex display to ensure it is truly responsive. But I am happy with whatever you folks prefer

**Comment by betatim** [comment]
I don't have a strong opinion on how to fix this (my CSS knowledge is too small). I do think it is worth investigating if we can fix things by removing custom CSS or passing it on to upstream. This reduces the amount of stuff we have to look after and fixes it for others as well.

In the interest of not stalling the PR we can always merge some local fixes, then upstream it and circle back on remove what we added locally.

**Comment by betatim** [comment]
Merging as it looks good to me on desktop and (simulated) mobile.

**Pull request merged**
