### PR TITLE
[MRG] Add and use new logo

### LINKED ISSUE #455: Proposing a logo for repo2docker
repo2docker doesn't have a logo which means its documentation page looks somewhat blank and makes it tricky to represent on slides. Also, what serious project doesn't have a logo :) Here is a proposal arrived at in #423:

46944629-441e4c00-d0be-11e8-87f8-a1212f6b5ccc

To move this forward at a steady but consistent pace the idea is to agree the basic ideas of the logo (individual pages with a fork symbol on them (representing the repo) and a container) and then:

* Colour scheme (e.g. do we want to adopt any of the Jupyter colors?)
* Structure and layout

Like the code and documentation this logo doesn't have to be perfect on day one and the expectation is that we'd keep tweaking it for a while.

What do you think of this? If you'd like to change something can you try and make a specific suggestion for what to change and how. This would help us in actually making it happen. You can check #423 for how things evolved, other ideas and inspirations that lead to where we are now.

This issue will stay open for at least 5 November 2018. Unless there are strong objections by that time this would become "the logo".

here's a link to the raw logo files: https://github.com/jupyter/repo2docker/files/2548509/repo2docker_v2.zip

### PR DESCRIPTION
**Pull request by betatim**
Closes #455 

README preview: https://github.com/jupyter/repo2docker/blob/a9c80b0af41ae26ce9c3006424387268490c1c70/README.md

Docs preview: https://11-90722372-gh.circle-artifacts.com/0/html/index.html

### CODE REVIEW

**Comment by betatim** [comment]
Let's merge this and then figure out the path to the PNG that is referenced in the README.md. Currently that is (I think) referencing a file on a branch in my repo. I don't know how to find out what that URL will be after merging this, hence the double step.

**Comment by willingc** [comment]
FYI Cal Poly folks, @ellisonbg @tgeorgeux @zsailer @Ruv7

**Comment by betatim** [comment]
In #455 we originally wrote "5 November" but there is no rush.

How about putting comments/thoughts which aren't blockers but should be addressed at some point in #455 instead of here?

**Comment by choldgraf** [comment]
ahhh right - I guess I "forgot forgot the 5th of november" lol...let's leave it up a bit longer in case the cal poly folks would like to share their thoughts

**Comment by choldgraf** [comment]
For anyone who's arriving at this PR for the first time:

* [Here's the original logo open design issue](https://github.com/jupyter/repo2docker/issues/423)
* [Here's the issue proposing a specific design](https://github.com/jupyter/repo2docker/issues/455)...we left it in an "open comment period" for ~10 days to get feedback, but didn't get much. I think we should have "@" notified more people

This PR is now a "final design" proposal to be merged in to the repo.

**Comment by willingc** [comment]
> we left it in an "open comment period" for ~10 days to get feedback, but didn't get much. I think we should have "@" notified more people
Probably a good practice to always notify (@-mention) @ellisonbg @tgeorgeux @Ruv7 @ZSailer as a courtesy when there are UI/UX logos, visuals, branding being changed.  Let's give it 48 hours for these folks to chime in if desired. After that, I think the change can be merged with no objections.

**Comment by choldgraf** [comment]
+1 to giving it several days! Sorry if this went under the radar for some folks.

**Comment by choldgraf** [comment]
friendly ping on this - think that we can move things forward here?

**Pull request merged**
